//
// Generated file, do not edit! Created by opp_msgtool 6.0 from serverStatusMsg.msg.
//

#ifndef __SERVERSTATUSMSG_M_H
#define __SERVERSTATUSMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ServerStatusMsg;
/**
 * Class generated from <tt>serverStatusMsg.msg:2</tt> by opp_msgtool.
 * <pre>
 * packet ServerStatusMsg
 * {
 *     bool busy;
 *     int priority = 0;
 * }
 * </pre>
 */
class ServerStatusMsg : public ::omnetpp::cPacket
{
  protected:
    bool busy = false;
    int priority = 0;

  private:
    void copy(const ServerStatusMsg& other);

  protected:
    bool operator==(const ServerStatusMsg&) = delete;

  public:
    ServerStatusMsg(const char *name=nullptr, short kind=0);
    ServerStatusMsg(const ServerStatusMsg& other);
    virtual ~ServerStatusMsg();
    ServerStatusMsg& operator=(const ServerStatusMsg& other);
    virtual ServerStatusMsg *dup() const override {return new ServerStatusMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getBusy() const;
    virtual void setBusy(bool busy);

    virtual int getPriority() const;
    virtual void setPriority(int priority);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ServerStatusMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ServerStatusMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ServerStatusMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<ServerStatusMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SERVERSTATUSMSG_M_H

